name: Security Scan

on:
  push:
    branches:
      - master

jobs:
  scan-docker-image:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v3

      
      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      
      - name: Run Security Scan with Trivy
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: my-app:latest
          format: table  # Çıktıyı tablo olarak göster

      # 4. Tarama Sonucu Mesajı
      - name: Notify Scan Result
        run: echo "Security scan completed!"
